name: green
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  liquid_progress_indicator: ^0.4.0
  qr_flutter: ^4.1.0
  simple_circular_progress_bar: ^1.0.2
  syncfusion_flutter_gauges: ^24.2.9
  ticket_widget: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/welcome.jpg
