name: green
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  build_runner: ^2.4.8
  camera: ^0.10.5+9
  cloud_firestore: ^4.15.10
  eva_icons_flutter: ^3.1.0
  firebase_core: ^2.27.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  liquid_progress_indicator: ^0.4.0
  lottie: ^3.1.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  shared_preferences_android: ^2.2.1
  simple_circular_progress_bar: ^1.0.2
  simple_progress_indicators: ^0.2.0
  syncfusion_flutter_gauges: ^25.1.35
  ticket_widget: ^1.0.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/
